### ISSUE TITLE
Suggestion: Option to save backup files next to FM files

### ISSUE THREAD

**Issue by maxigaz** [FenPhoenix/AngelLoader#49]
I've just tried out AngelLoader v1.4, and noticed that after setting the backup path in the options, I can’t unset it. Also, as I can see, AngelLoader can load backup files in the FM archives (saved by fmsel).

Would it be possible to allow the user to save the backup there, next to the FM files, as well?

**Comment by FenPhoenix** [comment]
You're right, the backup path being required is sort of weird and is a holdover from when all the other fields used to be required too. It's not really necessary, I would just have to add checks and a warning box if no backup path is set. 
As for allowing backups next to FMs, the reasons I didn't do that are:
- I wanted to leave other loaders' save backups alone and not overwrite them, just in case.
- Because FMSel and NDL both require separate FM archive folders per-game, there's only ever one location where backups go, but AL allows multiple archive dirs, and so allowing save backups in any or all of them sounded like a mess waiting to happen.
- If you import saves from DarkLoader, AL will create a "DarkLoader" subdirectory in the backup directory where it will copy DL's saves. That's so if you uninstall the copy of Thief where DarkLoader put its "allsaves" directory, AL will still be able to use your DL saves. Putting that in one of the FM archive dirs also sounded like a mess waiting to happen.

You're right that AL does in fact automatically use your old save backups if no newer ones exist, in order to provide an "it just works" experience to the user coming from another loader. But the assumption there is that there will only ever be one archive folder per game if you're coming from one of the other NewDark-compatible loaders (because they all require that), so we can be virtually certain we're using the right backup file (because there should only ever be one). But if we allow backup files in the archive dirs, now we have to decide which one to put them in, and we have the potential for there to be multiple backup files for the same FM. I'm a little uneasy about that. I like the "liberal in what you accept, conservative in what you send" approach where we leave things cleaner than they were before. I guess I could say "you have to have only one FM archive dir defined" but that sounds like a crappy hack. I'm not sure.

**Comment by maxigaz** [comment]
The reason I brought this up is because this reminded me of RetroArch, where you have the ability to specify a path for the save files or let them be created next to the ROM file currently loaded. In this case, I don’t have an “archive path” set for where the ROMs are; RA checks only the path of the ROM file in question (as far as I know). So, the potential issue with multiple backup files in AL could be solved if it checks only a single archive file, maybe?

Is there any difference between the format/structure between fmsel’s and AL’s backups? If they are different, it makes sense not to overwrite the ones coming from fmsel, indeed. (When I originally checked the size of the two versions, they *seemed* identical in the file browser I’m using (e.g. 11M), but looking inside those zip files now, I can see that some of them contain `startmis.sav` when backed up from AL, but not from fmsel. For other FMs, there’s no `startmis.sav` in neither cases.)

Anyway, even if there has to be a separate folder for the backups, it’s not a big deal. I still like AngelLoader a lot (running on Manjaro Linux through Wine) and I appreciate your work. :)

**Comment by FenPhoenix** [comment]
Whenever AL needs to find an archive file, it just searches through all the archive folders until it finds one whose name matches and then just uses that. It's possible - though probably unlikely in practice? - for there to be duplicate FMs archives with the same name if there are multiple archive folders. AL has no way to know one from another if that's the case, it just uses the first one it finds. But yeah, I guess it could just do the archive lookup and use the folder of the first one it finds and be right 99% of the time.

AL uses the same backup format as FMSel. The presence of startmis.sav in AL's backups is an oversight, I didn't realize FMSel excluded that one. I can't find any information about that file at all on TTLG - only two mentions and neither sheds any light on it. But from the name I would assume it's a "start-of-mission" save, except it doesn't seem to show up anywhere in-game and doesn't seem to be used(?). I believe it gets created when you start playing an FM. FMSel is made by the same people who made NewDark so they must know what the file does, and if they've chosen to exclude it from backups then that must mean it's unimportant and not required in any way. They probably excluded it to keep the backup files tidy. I'll do the same.

Also, you're running AngelLoader on Linux? I'm amazed it works! We tried that during beta testing and it wouldn't even show the window properly. Wine .NET support must have improved since a year ago?

**Comment by maxigaz** [comment]
> Also, you're running AngelLoader on Linux? I'm amazed it works! We tried that during beta testing and it wouldn't even show the window properly. Wine .NET support must have improved since a year ago?

Yes. :) I’ve been playing the first three Thief games for 7 years exclusively under Linux. .NET support has been a hit and miss from my experience as well, which is the main reason I’ve been sticking to using FmSel. (I heard about another FM loader also based on .NET a while ago, but I don’t remember what it was.)

Anyway, there are two ways of running .NET applications through Wine:

1. Through Mono, the open source implementation of the .NET framework for Linux.
2. With the official libraries from Microsoft (installed through `winetricks`, I assume the package `dotnet472` is what’s needed here).

I’ve only tried AL with Mono so far, with Thief Gold and Thief 2. There are minor visual glitches with the tooltips and, in certain scenarios, the program even crashes (like selecting text in the FM README and right clicking on it), but other than that, it’s very usable.

Recently, I realised that I can install .NET through winetricks as well (which I couldn’t do in the past), and I believe it’s entirely possible that the glitches mentioned above will go away this way. (At least this is what I had to do to make Open Rails, a free .NET-based game, fully playable.)

**Comment by FenPhoenix** [comment]
Oh wow, I thought a program had to be compiled specifically for Mono. I had no idea you could just run it like that!

On that topic, I could make AL properly cross-platform by using .NET Core, except for two showstopping issues: Windows Forms (the UI it uses) doesn't exist on Linux, and the Microsoft RichEdit control (used for displaying readmes, which includes .rtf files) doesn't exist on Linux. For the first issue, Avalonia looks promising (but it's still in beta) and for the second... well, that's tougher. I might have to implement my own .rtf parser, and the fact that companies license those for hundreds of dollars should tell you something about that :) Still, I'd like to do it one day, challenging though it may be. It would really set AL free of Microsoft's tyranny.

**Comment by maxigaz** [comment]
I'm not knowledgable in .NET programming, but from my experience, you can run .NET applications through Mono *with* and *without* Wine. Without Wine—running `mono AngelLoader.exe`—immediately throws me an unhandled exception and that’s it. So, I guess something else needs to be done for that to work.

I know [Jazz 2 Resurrection](http://deat.tk/jazz2/) has two .exe binaries, each of which can be run in both Windows and Linux Mono natively. I don’t know how it works, but in case you’re interested, feel free to take a look at that.

I don’t know how much work it takes, but if you can make any Linux-specific adjustments (now matter how small they are) to make it run better for penguin gamers, like me, I’m sure it it will be *very* appreciated.

**Comment by FenPhoenix** [comment]
I'm wanting to set up Linux and just do a bit of testing to see if I can smooth things out. Would you mind telling me about your setup? What distro, wine and mono version and how exactly you installed them? I'm afraid I constantly run into a brickwall trying to install things (wine and .net at least) in Linux. Always with the "unmet dependency" this and the "incomprehensible error screw you" that :( :( and the site just says "install the unmet dependencies then bro, unless you can't in which case install some other thing unless you can't, and then oh well I guess you're stuck bro" :(

Just want to get it set up so I can be of assistance...

**Comment by maxigaz** [comment]
> Would you mind telling me about your setup? What distro, wine and mono version and how exactly you installed them?

Sure. I’m running Manjaro Linux (64 bit edition). Originally, I installed the KDE Plasma edition, which I still have and use it daily (although it’s heavily customised). I recommend either that or the XFCE edition (somewhat more lightweight but still very usable), both of which can be downloaded from [here](https://manjaro.org/download/).

As for Wine and Mono, I have the packages `wine` and `wine-mono` installed. You can get them in the graphical application for managing packages (Octopi or Pamac), or in the terminal running the following:

```
sudo pacman wine wine-mono
```

Once it’s all installed, navigate to AL’s directory and run `wine AngelLoader.exe` in the terminal.

> Always with the "unmet dependency" this and the "incomprehensible error screw you" that :( :( and the site just says "install the unmet dependencies then bro, unless you can't in which case install some other thing unless you can't, and then oh well I guess you're stuck bro" :(

Do you mean the website or GitHub page of Lutris, by chance? If you mean [this page](https://github.com/lutris/docs/blob/master/WineDependencies.md) specifically, first of all, you can skip all of that if you use one of the methods I described above, because that automatically grabs all the required dependencies. You don’t even need Lutris, only if you want some convenience features not provided by Wine (like per game configuration, keeping multiple Wine versions with some hacks etc.), but even then, if you have `wine` and `wine-mono` installed  through the package manager, Wine versions installed through Lutris should work as well.

I hope that helps.

**Comment by FenPhoenix** [comment]
Thanks for the detailed answer. I'll get that setup going and see how I get on.

**Comment by FenPhoenix** [comment]
I'm getting a glitched and hardlocked main window when I start AngelLoader. The Initial Settings window works fine, but the main one is half-drawn and doesn't respond to closing. I have to kill it manually. It's running through Wine and I installed wine-mono too. I'm running in a VirtualBox VM. I dunno?

**Comment by maxigaz** [comment]
I also have various minor glitches (like tooltips or the context menu disappearing), but I’ve never had hardlocked or unresponsive windows in AL; only crashes when I try to highlight something in the FM readme, or sometimes when fiddling about in the right sidebar. Other than that, AL 1.4 and 1.4.1 are usable here.

I’m not sure if running it in VirtualBox is the cause, but it’s not impossible either. If you have a spare USB drive, you could try turning it into a [LiveUSB](https://manjaro.org/support/firststeps/#making-a-live-system), and see if it makes a difference. You can even install wine inside it for testing until you reboot. (I don't know how much RAM this needs though.)

If you *do* get better results in a live session, then it might be worth considering having a dualboot system, where you install Linux on a separate partition while keeping your existing Windows setup on another. I know this is not something everyone would be willing to do, but when a VM is not enough and you’re seriously thinking about working with Linux, this is the way to go.

There’s yet another option I can think of—which you may not like—which is porting AL to Qt/C++ or PyQt. The advantages include identical behaviour across all platforms whenever possible, great visual integration (so it actually looks and feels like a native app), and great performance. The disadvantage, of course, is that you need to become familiar with another programming language and rewrite the program from scratch. Again, I understand if you find that it’s too much work and you don’t want to do this—at least not alone—although if you want to prioritise cross-platform support, this is most likely the best move.

**Comment by FenPhoenix** [comment]
Actually I've been thinking about a native-code rewrite for some time now. Not only for cross-platform support, but also because I don't like where .NET is going - .NET Core 3 (and soon, .NET 5) is the future, but it's between 2x to 10x slower all-around (the main window init takes ~450ms on Core 3 vs. ~45ms on Framework 4.7.2, for example! Find-new-FMs takes twice as long, etc. See #43 ) and although .NET Framework 4.8 is "still supported", it's maintenance-only and I'm definitely on a dead-end track with it. I need to learn a new language, and I've been contemplating C/C++ or Rust. The former being more directly compatible with libraries (UI etc.), the latter probably being nicer/saner to use even with the borrow checker friction.

I actually do like the idea of a rewrite, it's just that I've never dealt with "unsafe" memory before. No experience with managing allocation/deallocation/pointers etc. manually. I'm scared of it really, is the thing. People say that memory bugs are rampant and hard to find etc. Don't know how true that really is. There are people like [Casey Muratori](https://hero.handmade.network/episode/code) who will tell you it's actually not very hard, but he's making games where all data is known and controlled and he can grab one huge block of memory at startup and never worry about it again. AngelLoader, being more or less a "productivity app" if you will, is the polar opposite - it needs to deal with tons of different formats of other peoples' data that it has little to no idea about, and it practically does nothing BUT string processing, which in terms of memory is about as dynamic as you can get.

It's true AngelLoader_Stub is written in C++ and the world didn't end, so that's a start. But that file is really really small and even if there are memory leaks it doesn't matter because it runs for like 10 milliseconds and then exits. Anyway, I'm actually making some moves to get away from .NET and Windows, starting with writing an RTF-to-plaintext converter so I can remove the RichEdit dependency in FMScanner. After that, I can maybe start rewriting small portions of AngelLoader to get comfortable. I also just want to learn how to write the things I currently use other peoples' libraries for - RTF parsing, zip file structure reading, etc. I just like to really learn and know and be able to write things myself even if I "don't have to". First because it's fun and empowering, and also because you never know when relying on somebody else's code will leave you in a lurch all of a sudden (like .NET Core being disastrously slow).

**Comment by maxigaz** [comment]
> I actually do like the idea of a rewrite, it's just that I've never dealt with "unsafe" memory before. No experience with managing allocation/deallocation/pointers etc. manually. I'm scared of it really, is the thing. People say that memory bugs are rampant and hard to find etc.

I’m not sure if it’s related (because I have only basic experience with C++), but I can tell you that Qt takes care of garbage collection automatically, so you don’t need to worry about memory not freed up once a task is done.

**Comment by FenPhoenix** [comment]
Closing this for now as it kind of wandered off and I guess the original question has been answered.
