### ISSUE TITLE
Realtime UI for translators

### ISSUE THREAD

**Issue by FenPhoenix** [FenPhoenix/AngelLoader#50]
This was suggested in the TTLG thread a while ago. By pulling apart the UI and converting it to passive-view (with an actually good reason other than coding dogma, yay!) and then sticking it in a separate .dll, I could make a translation app that uses the UI so translators can see their translations in realtime and without having to sometimes dig deep into functionality that might be destructive or that they might not be able to see. We could allow the translator to see every section of the UI harmlessly (example: uninstalling FMs, converting audio files, viewing uncommon error scenarios that might be difficult or impossible to make happen in the regular app, etc).

**Comment by maxigaz** [comment]
This wouldn’t affect the format of the translation file itself, right?

I’m asking because having it as plain text allows translators to use their favourite text editor. (Also, I’ve begun working on my own translation, I’ve just been putting it off lately.)

**Comment by FenPhoenix** [comment]
No, the format would stay the same. Not even certain if this UI thing is a good idea. Maybe the English strings are clear enough already, but I'm just thinking it may be helpful to give people a way to see text in context but without messing around playing havoc with their personal setup to do it. I've also gotten a few updated translations from people which they've called "improved" translations, so I wonder if maybe people are having trouble sometimes? Not a translator myself, but trying to consider things.

**Comment by maxigaz** [comment]
> No, the format would stay the same. Not even certain if this UI thing is a good idea.

Oh, OK. That’s great to hear.

> Maybe the English strings are clear enough already, but I'm just thinking it may be helpful to give people a way to see text in context but without messing around playing havoc with their personal setup to do it. I've also gotten a few updated translations from people which they've called "improved" translations, so I wonder if maybe people are having trouble sometimes?

From what I’ve seen, the strings *are* clear. You’ve even included group names like `[ProgressBox]`, which is very helpful in understanding the context. So, if someone sends you an updated version, I imagine it can be either because some of the translated strings are longer and there’s not enough space to display them correctly (which I *have* come across once, actually), or it’s just like any other skill: you get better over time. (Sometimes I roll my eyes at my own mistakes from years ago.)

Out of curiosity, what languages are available already? Could you include them [here](https://github.com/FenPhoenix/AngelLoader/tree/master/AngelLoader/Languages), for example, so that anyone interested can see the current state? I can help with Hungarian (my native language) and Spanish, although if someone has already started any of these, I’d prefer to let them finish.

**Comment by FenPhoenix** [comment]
Oh yeah, I used to have languages there I think, but I removed them for some reason. It was probably because English.ini would be the latest dev version but everything else would be whatever the latest thing is I've received, and that seemed weird maybe? Maybe I could just put a readme in there saying that.

**Comment by FenPhoenix** [comment]
Okay, put the other languages in. As you can see, Spanish is taken, but Hungarian is up for grabs.

**Comment by maxigaz** [comment]
Thanks a lot! I'll send you a pull request when I'm done. :)

**Comment by FenPhoenix** [comment]
I've commented the English.ini file more thoroughly in places I feel might be unclear or have some vagueness to them. That'll improve things some amount at least without the large amount of work separating the UI and all
