### ISSUE TITLE
Question: String for date format options in English.ini

### ISSUE THREAD

**Issue by maxigaz** [FenPhoenix/AngelLoader#55]
As I was translating `English.ini`, I noticed that two of the strings say `Current culture short` and `Current culture long`, appearing in the Options. Wouldn’t it be better to display `System settings, short`? (Maybe it’s just me, but I think it sounds clearer this way.)

Also, there’s a string for an error that says, `The date and time is outside the range of dates supported by the calendar used by the current culture`. When does this normally appear? Does this appear when an FM contains a release date like “the 33rd of December”? (First, I thought it has to do with the custom format you can set in the Options, but using the drop-downs, no matter what I set, it all appears fine without any errors.)

**Comment by FenPhoenix** [comment]
1. "System settings, short" etc.? That sounds less clear to me, but feel free to translate it in what way you think best. "Current culture" sounds like programmer-speak (because it is), but I couldn't think of anything better to call it at the time. Actually maybe "Current locale" would be better. Or "System locale". Dunno. "System locale, short" maybe?

2. These two errors:
`FMDisplay_ErrorInvalidDateFormat=Invalid date format.`
`FMDisplay_ErrorDateOutOfRange=The date and time is outside the range of dates supported by the calendar used by the current culture.`
are displayed if you choose a custom date format and something is invalid about it. I'm actually pretty sure this might be impossible due to checks done elsewhere, and I even say so in the code:

            // TODO: Date error checking:
            // It's impossible to get an ArgumentOutOfRangeException as long as our readonly example date is valid.
            // It's probably impossible to get a FormatException too (because we handle invalid formats in the
            // config reader and reset to default if they aren't valid) but not 100% certain.

Normally I wouldn't even have language strings for this sort of thing (I would just log the error in English), but it's just that this error would block the Settings window from closing if it happened, and I wanted to at least give the user some indication of why in that case. But I'm pretty sure it can never happen in practice. I should probably just remove those strings.

(But this is what I mean by giving translators more context ;P)

BTW: It's not possible to cause an FM's date (any of them) to be invalid while using the application. You would have to go into FMData.ini and manually mess them up, but they're checked for validity when they're read in, and if invalid they're just ignored and set to nothing. So no worries about that.

**Comment by maxigaz** [comment]
I like the sound of “System locale” the most out of these. (Actually the word “locale” did cross my mind, I just wasn’t sure how well it’s known to an average gamer who speaks English nowadays.)

> (But this is what I mean by giving translators more context ;P)

Fair enough. :smile: Thanks for the explanation!
