### ISSUE TITLE
Request: GUI optimization, move sidebar to the bottom, move Scan all FMs, Settings & Import from to Main menu

### ISSUE THREAD

**Issue by githubuser181226** [FenPhoenix/AngelLoader#71]
Hi.
Please, consider moving the entire sidebar with its tabs to the bottom where the readme is, and put readme on another tab.
Also join together all the top toolbar commands.
Check attached mockup.

![angelloader-sidebartabs-onthebottom](https://user-images.githubusercontent.com/46164484/112240241-43535200-8c48-11eb-91b1-287343dc28d8.png)

IMO this a much cleaner look and you can display all the columns on the list without hiding the sidebar and/or scrolling the list horizontally.

Also this removes unnecessary controls (toggle button, spliter) and fixes my other issue #70 with the sidebar.

Cheers.

**Comment by githubuser181226** [comment]
Please consider these (further) GUI optimizations:
1. Remove "Scan all FMs..." button, add "Scan all FMs..." command to the Main menu
2. Remove "Import from..." button, add "Import from..." to Main menu
3. Remove "Settings..." button, add "Settings..." to Main menu
Mockup attatched.
![angelloader-addtomainmenu](https://user-images.githubusercontent.com/46164484/112242870-e27a4880-8c4c-11eb-8bcd-38b7361e0ec8.png)
Cheers.

**Comment by githubuser181226** [comment]
Also an important question: what's the point of having "Scan all FMs..." at all (aside from the additional scan options), when there's already the "Refresh from disk" command in the top toolbar?

**Comment by FenPhoenix** [comment]
1. That's a big change and I wouldn't want to just make it randomly (I _hate_ when apps change what I'm used to). I mean, there are advantages - way more space for the tab sections, for one, which I'll need to for the new mod management system I want to implement in the future. So, yeah, I mean I'll consider it, but making a huge change when _one_ person has requested it but I have many other users, it's something I'm extremely cautious about.

2. This one I agree with 100%. Those buttons are really dopey in the bottom bar and being larger than most other elements. I put them there because NewDarkLoader had them or something, or maybe some other loader, and I was trying to "look the same". But I've been wanting to move them into a menu for a while now, so I'll make a note to do that.

3. "Scan all FMs" is not the same as "Refresh from disk". "Refresh from disk" checks to see if new FM archives (or installed folders for that matter) have been added, pulls them into the list, and scans just the new ones IF they haven't been scanned before. (A scenario where you could pull in "new" FMs that _have_ been scanned before is if you were to delete an FM and then later re-add it, its data would still be in the database and it would be marked as "already scanned", so it would pull it into the list but not scan it again.) "Scan all FMs" scans all the FMs that are currently in the list (not checking for new ones) regardless of if they've been scanned before, and gives you options for what to scan for. Probably not a very commonly used feature, but it's there because again, I think NDL had that feature. Definitely it should go into a menu at the very least.

**Comment by githubuser181226** [comment]
Hello!
Thanks for the response, Mr. Fen.

>     1. That's a big change and I wouldn't want to just make it randomly (I _hate_ when apps change what I'm used to). I mean, there are advantages - way more space for the tab sections, for one, which I'll need for the new mod management system I want to implement in the future. So, yeah, I mean I'll consider it, but making a huge change when _one_ person has requested it but I have many other users, it's something I'm extremely cautious about.

It's your program. I don't think anyone would argue with you if you decided to do that or anything major, so long as it fixed issues rather than introduce new ones.

This was just my idea, mainly to "organize" the UI a bit to and for you to get rid of superfluous stuff, which I imagine only adds to the overall hassle when, for example, re-themeing the entire thing.

>        Like, maybe somebody likes to see the readme while doing stuff in the tabs. 

Are you sure it's a valid use case? I mean, other than for the developer of this program? =)
Because from my experience, and I'm just a player, who uses AngelLoader to play fanmissions, I rarely if ever even read readmes at all. The only time I look it up it is when it's a contest mission or there's no ingame introduction of any kind.
Same with any options in the sidebar - for me it's only useful if something is broken, so I could write that in the comment or tag it properly. The other single useful options is to run the game without the mods, and that's that.
Anything other in that section of the ui is not that usefull.
Most important things are gathered in the mission list.

Still, you could add an option to pop-up readme tab to a separate window. That way you would have best of both worlds.

>     2. This one I agree with 100%. Those buttons are really dopey in the bottom bar and being larger than most other elements. I put them there because NewDarkLoader had them or something, or maybe some other loader, and I was trying to "look the same". But I've been wanting to move them into a menu for a while now, so I'll make a note to do that.

I think big buttons bellow are ok as long as they are useful there.
Anything related to options IMO should not be there. That's why programs have main menus / main toolbars.

I know it's a darkloader thing, but IMO mixing useful stuff (ie. Play mission) with completely random thing like "Import from..." I literally never used in my entire life as a taffer is just wasteful.

I'd rather make that bar context-aware and not show things that don't relate to currently selected mission.

>     3. "Scan all FMs" is not the same as "Refresh from disk". [...]

There are 3 buttons/command to scan/refresh/whatever - two up top and that one on the bottom, and it's just too confusing to remeber which does what, because of that whenever I change anything in my mission folders I always rather re-start the program then click any of the buttons.

If anything there should be only 1 such command visible at all times and if other two are really that different and worth preserving, they should be placed somewhere else - maybe an entirely separate section / window / main menu submenu dedicated solely to importing, scanning, rescanning, refreshing wathever would be in order.

But as I pointed out these are just minor things to consider.

Most people probably don't even care that much or at all, because what they actually want from the program is to run fan missions, which it does perfectly, and I can understand that. 

Then again, if that was the case, I think it really would be great if the program had a single simpler (to understand) process, you could re-launch with that single ("refresh database") button, to refresh and/or read what's necessary from the disk.

Again, it's all things to consider, if you ever decided to fresh up the UI.
Kudos for your hard work.
Cheers,
